### ISSUE TITLE
Readme / Integrations Issues

### ISSUE THREAD

**Issue by EasilyBoredEngineer** [930913/ld2410-ble#4]
Hi There 930913 -

It was great to see this sensor integrated in the latest release.

The features looked great, so I came over here to have a look - but the readme and issues section looks a bit spartan, so was hoping you might be able to direct me to a more thorough description of how to use this project - I've already got one of these sensors integrated (and they're outstanding), but not via BLE - just via the GPIO output of the sensor.

Any further info you could provide would be massively appreciated - M

**Comment by 930913** [comment]
If you have a Bluetooth version of the module (B/C) and you have a supported Bluetooth adaptor or proxy already configured, it should automagically discover and offer to configure the device in the Device and Services page.

**Comment by EasilyBoredEngineer** [comment]
ah thankyou @930913 - I was hoping to use this with ESPHome rather than directly with HA - I got my wires crossed.
